### ISSUE TITLE
Dead link for TFE/TFC run task demo

### ISSUE THREAD

**Issue by sbibow** [infracost/docs#259]
On the page <https://www.infracost.io/docs/integrations/terraform_cloud_enterprise/#3-results> there is a link with an example "here", which lead to <https://dashboard.infracost.io/results/285db4b2-1467-41c0-a162-382ae7f87e89?token=932c8505d6cd3dd7c3cba4d45188eeec9988976ae0d366ccc5ae813ed1b4fc395dfba94d14d54babef943c23042787f66076f04a29a37dced8d0ae963e5cefd5>.

The page is not found, either because the project does not exist or the token has expired.

**Comment by alikhajeh1** [comment]
@sbibow thanks for reporting this! I fixed the link, it should be pointing to https://dashboard.infracost.io/share/p7696wnyb4zmdvpr2k4x0nwq7p8pd2tz
