### ISSUE TITLE
Add instructions for Semaphore CI/CD platform to docs.

### ISSUE THREAD

**Issue by TomFern** [infracost/docs#363]
This proposal is to add instructions to configure Infracost with [Semaphore CI/CD](https://semaphoreci.com) to the [integration section of the docs](https://www.infracost.io/docs/integrations/github_app/).

We've tested Infracost with the CI/CD platform and it works great. I've [written a tutorial](https://semaphoreci.com/blog/infracost) on how to configure it on the Semaphore blog. 

If this proposal is approved I can volunteer to write the documentation (I work as a technical writer on Semaphore) or contribute with code/snippets, configuration files and screenshots.

Thank you
Tomas

**Comment by alikhajeh1** [comment]
Hi @TomFern - thanks! What do you think about hosting the docs on https://docs.semaphoreci.com/ so you can update/maintain it fully and we can link to it from https://www.infracost.io/docs/integrations/third_party_integrations/ ?

**Comment by TomFern** [comment]
Hey @alikhajeh1 thank you! I like this idea. We already have [multiple integrations](https://docs.semaphoreci.com/examples/tutorials-and-example-projects/) described our docs, so it would be easy to add a page about Infracost.

We'll work on it and let you know when it's online, so you may add a link on the Infracost docs.

**Comment by alikhajeh1** [comment]
@TomFern awesome - thanks! 🚀 
I've assigned this issue to myself to remember to setup the links when you're done. We can also link to your docs in our monthly update newsletter.

**Comment by alikhajeh1** [comment]
Thanks @TomFern! I'll take a look at this next week

**Comment by alikhajeh1** [comment]
@TomFern sorry for the delay - I added the link in https://github.com/infracost/docs/pull/451 that'll go live tmrw. A few comments on the article:
1. When installing the CLI, you can use `curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | INFRACOST_VERSION=v0.10 sh` to force the latest version of the v0.10 CLI to avoid breaking CI/CD pipelines when we introduce breaking changes in v0.11 but at the same time pickup the latest patch fixes and new resources.
2. In [this section](https://docs.semaphoreci.com/examples/estimating-cloud-costs-with-infracost/#estimates-on-github), I'm not quite sure how `baseline.json` file is being generated.

**Comment by TomFern** [comment]
Hi @alikhajeh1 thank you for adding the link and doing the review. I'll take care of fixing the issues you mentioned 🙇‍♂️

**Comment by alikhajeh1** [comment]
Thanks @TomFern!

**Comment by TomFern** [comment]
@alikhajeh1 thank you for the feedback. I fixed the docs on our side to reflect your comments.
